# Use uma imagem Python
FROM python:3.10-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para instalar as dependências
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código fonte para o container
COPY . .

# Exponha a porta onde o FastAPI rodará (default 8000)
EXPOSE 8000

# Comando para rodar o FastAPI com Uvicorn
CMD ["uvicorn", "app:app", "--host", "localhost", "--port", "8000"]
