# Use uma imagem oficial do Node.js como base
FROM node:20-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

ENV PORT 7000

# # Constrói o aplicativo Next.js para produção
RUN npm run build

# Expõe a porta que o Next.js irá rodar
# EXPOSE 3000
EXPOSE 7000

# Comando para rodar a aplicação
CMD ["npm", "start"]